### ISSUE TITLE
Have a error on jupyter notebook

### ISSUE THREAD

**Issue by Aja23i6** [vals/python-gprofiler#9]
Hi there,

When I import Profiler in jupyter, I have the error:

from gprofiler import GProfiler

ImportError: cannot import name 'GProfiler' from 'gprofiler' (/Users/.../miniconda3/lib/python3.7/site-packages/gprofiler/__init__.py)

I am wondering if you could tell me how to solve it?

Best,

**Comment by vals** [comment]
I think it's as simple as using lower case letters: try changing `GProfiler` to `gprofiler`.

**Comment by Aja23i6** [comment]
It works! Thank you!

**Comment by vals** [comment]
Happy to help!

**Comment by rboiarsky** [comment]
Hi, I just encountered this issue and switching to lowercase helped me for as well. I'm wondering if this changed at some point though, because my ultimate goal is to be able to use the `enrich` function in scanpy, which also has the line ` from gprofiler import GProfiler` with capitalization and thus throws an error. Additionally, the documentation for gprofiler-official shows the import statement with capitalization: https://pypi.org/project/gprofiler-official/ ...is this the same package as that one? Thanks

**Comment by vals** [comment]
No this is a different package.

For what it's worth I'm also using the `gprofiler-official` official package nowadays. But the PyPI entry doesn't link to any github page for some reason, so no idea who maintains it or how to contact them.
